name: CI DevSecOps Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-analyse-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Analyse SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=UlysseBAC_devsecopsdemo
          -Dsonar.organization=ulyssebac
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Build Maven
      run: mvn clean package -DskipTests

    - name: Connexion DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build image Docker
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devsecopsdemo:latest .

    - name: Push image Docker
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devsecopsdemo:latest
